"""Write the iOS app's server settings (AppConfig.swift) from Backend/.env.

The app needs the Supabase project address and the PUBLISHABLE key, which
Supabase designs to be shipped inside apps (it can only call app_forecast;
every table is protected by row level security). Secret keys are refused,
because the generated file is committed to the public repository.

Run from the Backend folder after changing SUPABASE_PUBLISHABLE_KEY in .env:
    .venv/bin/python -m scripts.write_app_config
"""

from pathlib import Path

from dotenv import dotenv_values

BACKEND = Path(__file__).resolve().parent.parent
OUTPUT = BACKEND.parent / "iOS" / "North Star" / "North Star" / "Data" / "AppConfig.swift"


def main() -> None:
    env = dotenv_values(BACKEND / ".env")
    user = env["DATABASE_URL"].split("://", 1)[1].split(":", 1)[0]  # postgres.<project id>
    project_id = user.split(".", 1)[1]
    key = (env.get("SUPABASE_PUBLISHABLE_KEY") or "").strip()

    if key.startswith("sb_secret_") or "service_role" in key:
        raise SystemExit("That is a SECRET key. Use the publishable (sb_publishable_...) or anon key instead.")
    if key and not (key.startswith("sb_publishable_") or key.startswith("eyJ")):
        raise SystemExit("SUPABASE_PUBLISHABLE_KEY does not look like a Supabase publishable or anon key.")

    OUTPUT.write_text(f'''import Foundation

// Generated by Backend/scripts/write_app_config.py from Backend/.env. Do not edit by hand.
//
// These are PUBLIC values: Supabase's publishable key is designed to be built
// into apps. It can only call the read-only app_forecast function; all tables
// are protected by row level security.
enum AppConfig {{
    static let supabaseURL = URL(string: "https://{project_id}.supabase.co")
    static let supabasePublishableKey = "{key}"
}}
''')
    print(f"Wrote {OUTPUT.relative_to(BACKEND.parent)} (publishable key {'set' if key else 'NOT set yet'})")


if __name__ == "__main__":
    main()
