"""Write the iOS app's server settings from Backend/.env.

1. AppConfig.swift (committed): the Supabase project address and the
   PUBLISHABLE key, which Supabase designs to be shipped inside apps (it can
   only call app_forecast; every table is protected by row level security).
   Secret keys are refused, because this file is in the public repository.
   Also the route server's address.
2. RouteServer.plist (NOT committed, listed in .gitignore): the route server's
   app key (NORTHSTAR_APP_KEY, the same value Render generated). It ships
   inside the app, so it is not a true secret, but keeping it out of the public
   repository stops anyone from simply copying it to use our Google allowance.

Run from the Backend folder after changing a key in .env:
    .venv/bin/python -m scripts.write_app_config
"""

import plistlib
from pathlib import Path

from dotenv import dotenv_values

BACKEND = Path(__file__).resolve().parent.parent
OUTPUT = BACKEND.parent / "iOS" / "North Star" / "North Star" / "Data" / "AppConfig.swift"
ROUTE_KEY_OUTPUT = OUTPUT.parent / "RouteServer.plist"
ROUTE_SERVER_URL = "https://north-star-api-w5xt.onrender.com"


def main() -> None:
    env = dotenv_values(BACKEND / ".env")
    user = env["DATABASE_URL"].split("://", 1)[1].split(":", 1)[0]  # postgres.<project id>
    project_id = user.split(".", 1)[1]
    key = (env.get("SUPABASE_PUBLISHABLE_KEY") or "").strip()

    if key.startswith("sb_secret_") or "service_role" in key:
        raise SystemExit("That is a SECRET key. Use the publishable (sb_publishable_...) or anon key instead.")
    if key and not (key.startswith("sb_publishable_") or key.startswith("eyJ")):
        raise SystemExit("SUPABASE_PUBLISHABLE_KEY does not look like a Supabase publishable or anon key.")

    OUTPUT.write_text(f'''import Foundation

// Generated by Backend/scripts/write_app_config.py from Backend/.env. Do not edit by hand.
//
// These are PUBLIC values: Supabase's publishable key is designed to be built
// into apps. It can only call the read-only app_forecast function; all tables
// are protected by row level security.
enum AppConfig {{
    static let supabaseURL = URL(string: "https://{project_id}.supabase.co")
    static let supabasePublishableKey = "{key}"
    /// The route planner server (its app key is in RouteServer.plist, which is not committed).
    static let routeServerURL = URL(string: "{ROUTE_SERVER_URL}")
}}
''')
    print(f"Wrote {OUTPUT.relative_to(BACKEND.parent)} (publishable key {'set' if key else 'NOT set yet'})")

    app_key = (env.get("NORTHSTAR_APP_KEY") or "").strip()
    with open(ROUTE_KEY_OUTPUT, "wb") as f:
        plistlib.dump({"AppKey": app_key}, f)
    print(f"Wrote {ROUTE_KEY_OUTPUT.relative_to(BACKEND.parent)} (app key {'set' if app_key else 'NOT set yet'})")


if __name__ == "__main__":
    main()
