import Foundation

// Generated by Backend/scripts/write_app_config.py from Backend/.env. Do not edit by hand.
//
// These are PUBLIC values: Supabase's publishable key is designed to be built
// into apps. It can only call the read-only app_forecast function; all tables
// are protected by row level security.
enum AppConfig {
    static let supabaseURL = URL(string: "https://vrlibkfedffdnkbctvla.supabase.co")
    static let supabasePublishableKey = "sb_publishable_AmKsZ0YtqS0eMu0usGjIGw_IyLBP-sp"
}
